---
title: "Día 29: Gráfico de coordenadas paralelas con títulos de Real Madrid y Barcelona"
date: "06/06/2020"
output: html_document
---

Hoy haremos un gráfico de coordenadas paralelas con los títulos del Real Madrid y el Barcelona.

Como siempre, primero cargaremos los paquetes necesarios.

```{r load-libraries, message=FALSE, warning=FALSE}
library(tidyverse)
library(ggtext)

windowsFonts("Bahnschrift" = windowsFont("Bahnschrift"))
```

Importamos los datos obtenidos de Wikipedia y hacemos una pequeña transformación.

```{r load-data, message=FALSE, warning=FALSE}
data_raw <- read_csv("data/day29.csv", col_names = FALSE)

data_clean <- data_raw %>% 
                mutate(X2 = factor(X2, unique(X2), ordered = T))
```

Visualizamos.

```{r plot, message=FALSE, warning=FALSE}
ggplot(data_clean, aes(x = X2, y = X3, group = X1, colour = X1)) +
  geom_line(size = 1) +
  geom_point(size = 2) +
  labs(
    title = "Títulos conseguidos por <span style='color:#551a8b;'>Real Madrid</span> y <span style='color:#a50044;'>Barcelona</span>",
    caption = "Fuente: Wikipedia | @jantleon",
    x = "",
    y = ""
  ) +
  scale_color_manual(values = c("#a50044","#551a8b")) +
  scale_y_continuous(breaks = seq(5, 40, 5)) +
  theme_minimal(base_family = "Bahnschrift") +
  theme(plot.title = element_markdown(face = "bold", hjust = 0.5),
        axis.text.x=element_text(angle = 45, hjust = 1),
        legend.title = element_blank(),
        legend.position = "none",
        plot.title.position = "plot")

ggsave("plots/day29.png", width = 8)
```

